
# Exercises Section 6 Docker Stack

version: '3'
service:
  redis:
    image: redis
    networks:
      - back-end
    volumes:
      - redis-data:/var/lib/redis
    deploy:
      replicas: 1

  db:
    image: postgres:9.4
    networks:
        - back-end
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
          replicas: 1
          placement:
            constraints: [node.role == manager]

  vote:
    image: voting-app
    ports:
      - "5000:80"
    networks:
        - back-end
        - front-end
    deploy:
          replicas: 2
          update_config:
            parallelism: 2

  result:
    image: result-app
    ports:
        - 5001:80
    networks:
        - back-end
        - front-end
    deploy:
          replicas: 1

  worker:
    image: worker-app
    networks:
        - back-end
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
            delay: 10s

networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge

volumes:
  redis-data:
  db-data: