
# Process that monitors the pods determined by selector matchLabel

apiVersion: v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:

    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

    replicas: 3
    selector:
      matchLabels:
        type: front-end

# kubectl create -f replicaset-definition.yaml
# kubectl get replicaset
# kubectl delete replicaset myapp-replicaset

## Scale the number of replicas
# kubectl scale --replicas=6 replicaset myapp-replicaset
