version: 2
services:
    redis:
        image: redis
        networks:
            - back-end
    
    db:
        image: postgres:9.4
        networks:
            - back-end

    vote:
        image: voting-app
        networks:
            - front-end
            - back-end

    result:
        image: result
        networks:
            - front-end
            - back-end

networks:
  - front-end:
  - back-end: